### ISSUE TITLE
Hibersap Webapp Example

### ISSUE THREAD

**Issue by gvsrini** [hibersap/cuckoo-hibersap-example#3]
Do you have a simple Spring webapp example with Hibersap? Searched  a lot, but almost everything is linking to Cuckoo Resource Adapter and JBoss Forge which I really don't understand.

**Comment by cerker** [comment]
Hi, 

if you are looking for a simple hibersap-example without Cuckoo, please take a look at the documentation page under http://hibersap.org. Sorry no Spring and Web there but integrating Hibersap with Spring should be straightforward if you know Spring already.

If you have a running webapp example with Spring and feel like contributing it, we'd be pleased to add it to the examples in the hibersap repo here on GitHub.
